"use strict";
var topic = "Javascript Variables!";
console.log(topic);
topic = "Updated Value!";
console.log(topic);
var apples = 0;
apples += 1000;
apples += 100;
var mangoes = 200;
var allTogether = apples + mangoes;
console.log(allTogether);
